[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
opt-level = 3

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
memchr = "2.7.4"
atoi_simd = "0.16.0"
intmap = "3.0.0"